language: generic
sudo: required
servics:
  - docker

before_install:
  - docker build -t sangeetprasad/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true sangeetprasad/docker-react npm run test -- --coverage